### PR TITLE
Fix rebase issues

### PR DESCRIPTION
**Pull request by acroca**
I've found some issues with the recent rebase:
- Some imports were using `ethereum/go-ethereum` instead of `kowala-tech/kUSD`
- The state runner has dependencies with `/tests`, package we didn't import. It seems unnecessary for us, so I removed it.
- Some code in a simulated backend was wrong.

### CODE REVIEW

**Comment by acroca** [comment]
@rgeraldes is it necessary? The state runner has a dependency with some test code

**Comment by rgeraldes** [comment]
I'm not 100 % sure and that's why I think we should comment the code + add a note (@TODO).

**Comment by acroca** [comment]
We can also add a dummy implementation of the dependency from tests, so the staterunner doesn't change and as soon as #59 is done it'll all continue working. Makes sense?

**Comment by rgeraldes** [comment]
That works too!

**Comment by acroca** [comment]
Done, added a fake implementation of the dependencies, just to let it compile.

**Pull request merged**
